name: Java CI

permissions:
  id-token: write
  contents: write

on:
  push:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::329799773336:role/npiper-githubactions-role
        aws-region: eu-west-2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
        
    - name: Configure Git
      run: |
        git config --global user.name "${{ secrets.GHUBUILDSER }}"
        git config --global user.email "${{ secrets.GHBUILDEMAIL }}"

    - name: Build and Deploy
      run: |
        mvn clean install -Drevision=${{ github.run_number }}.$(git rev-parse --short HEAD) --settings .travis.settings.xml
        mvn site deploy scm:tag --settings .travis.settings.xml -Drevision=${{ github.run_number }}.$(git rev-parse --short HEAD) -Dusername=${{ secrets.GHUBUILDSER }} -Dpassword=${{ secrets.GHOAUTH_SECRET_TOKEN }}
      env:
        GIT_USER_NAME: ${{ secrets.GHUBUILDSER }}
        GIT_USER_EMAIL: ${{ secrets.GHBUILDEMAIL }}
        GITPW: ${{ secrets.GHOAUTH_SECRET_TOKEN }}
